package com.zj.dao.model;

import java.util.Date;

public class IdxInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.indexId
     *
     * @mbggenerated
     */
    private String indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.index_name
     *
     * @mbggenerated
     */
    private String indexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.index_type
     *
     * @mbggenerated
     */
    private String indexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.index_content
     *
     * @mbggenerated
     */
    private String indexContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.index_function
     *
     * @mbggenerated
     */
    private String indexFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.value_type
     *
     * @mbggenerated
     */
    private String valueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.value_unit
     *
     * @mbggenerated
     */
    private String valueUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_info.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.indexId
     *
     * @return the value of idx_info.indexId
     *
     * @mbggenerated
     */
    public String getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.indexId
     *
     * @param indexId the value for idx_info.indexId
     *
     * @mbggenerated
     */
    public void setIndexId(String indexId) {
        this.indexId = indexId == null ? null : indexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.index_name
     *
     * @return the value of idx_info.index_name
     *
     * @mbggenerated
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.index_name
     *
     * @param indexName the value for idx_info.index_name
     *
     * @mbggenerated
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.index_type
     *
     * @return the value of idx_info.index_type
     *
     * @mbggenerated
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.index_type
     *
     * @param indexType the value for idx_info.index_type
     *
     * @mbggenerated
     */
    public void setIndexType(String indexType) {
        this.indexType = indexType == null ? null : indexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.index_content
     *
     * @return the value of idx_info.index_content
     *
     * @mbggenerated
     */
    public String getIndexContent() {
        return indexContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.index_content
     *
     * @param indexContent the value for idx_info.index_content
     *
     * @mbggenerated
     */
    public void setIndexContent(String indexContent) {
        this.indexContent = indexContent == null ? null : indexContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.index_function
     *
     * @return the value of idx_info.index_function
     *
     * @mbggenerated
     */
    public String getIndexFunction() {
        return indexFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.index_function
     *
     * @param indexFunction the value for idx_info.index_function
     *
     * @mbggenerated
     */
    public void setIndexFunction(String indexFunction) {
        this.indexFunction = indexFunction == null ? null : indexFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.value_type
     *
     * @return the value of idx_info.value_type
     *
     * @mbggenerated
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.value_type
     *
     * @param valueType the value for idx_info.value_type
     *
     * @mbggenerated
     */
    public void setValueType(String valueType) {
        this.valueType = valueType == null ? null : valueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.value_unit
     *
     * @return the value of idx_info.value_unit
     *
     * @mbggenerated
     */
    public String getValueUnit() {
        return valueUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.value_unit
     *
     * @param valueUnit the value for idx_info.value_unit
     *
     * @mbggenerated
     */
    public void setValueUnit(String valueUnit) {
        this.valueUnit = valueUnit == null ? null : valueUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.created_by
     *
     * @return the value of idx_info.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.created_by
     *
     * @param createdBy the value for idx_info.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.created_at
     *
     * @return the value of idx_info.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.created_at
     *
     * @param createdAt the value for idx_info.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.updated_by
     *
     * @return the value of idx_info.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.updated_by
     *
     * @param updatedBy the value for idx_info.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_info.updated_at
     *
     * @return the value of idx_info.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_info.updated_at
     *
     * @param updatedAt the value for idx_info.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}