package com.zj.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class IdxValueManual {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.indexId
     *
     * @mbggenerated
     */
    private String indexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.sub_product_code
     *
     * @mbggenerated
     */
    private String subProductCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.reg_channel
     *
     * @mbggenerated
     */
    private String regChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.sub_channel
     *
     * @mbggenerated
     */
    private String subChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.value
     *
     * @mbggenerated
     */
    private BigDecimal value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idx_value_manual.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.id
     *
     * @return the value of idx_value_manual.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.id
     *
     * @param id the value for idx_value_manual.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.created_date
     *
     * @return the value of idx_value_manual.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.created_date
     *
     * @param createdDate the value for idx_value_manual.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.indexId
     *
     * @return the value of idx_value_manual.indexId
     *
     * @mbggenerated
     */
    public String getIndexId() {
        return indexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.indexId
     *
     * @param indexId the value for idx_value_manual.indexId
     *
     * @mbggenerated
     */
    public void setIndexId(String indexId) {
        this.indexId = indexId == null ? null : indexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.label
     *
     * @return the value of idx_value_manual.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.label
     *
     * @param label the value for idx_value_manual.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.org_code
     *
     * @return the value of idx_value_manual.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.org_code
     *
     * @param orgCode the value for idx_value_manual.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.product_code
     *
     * @return the value of idx_value_manual.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.product_code
     *
     * @param productCode the value for idx_value_manual.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.sub_product_code
     *
     * @return the value of idx_value_manual.sub_product_code
     *
     * @mbggenerated
     */
    public String getSubProductCode() {
        return subProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.sub_product_code
     *
     * @param subProductCode the value for idx_value_manual.sub_product_code
     *
     * @mbggenerated
     */
    public void setSubProductCode(String subProductCode) {
        this.subProductCode = subProductCode == null ? null : subProductCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.reg_channel
     *
     * @return the value of idx_value_manual.reg_channel
     *
     * @mbggenerated
     */
    public String getRegChannel() {
        return regChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.reg_channel
     *
     * @param regChannel the value for idx_value_manual.reg_channel
     *
     * @mbggenerated
     */
    public void setRegChannel(String regChannel) {
        this.regChannel = regChannel == null ? null : regChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.sub_channel
     *
     * @return the value of idx_value_manual.sub_channel
     *
     * @mbggenerated
     */
    public String getSubChannel() {
        return subChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.sub_channel
     *
     * @param subChannel the value for idx_value_manual.sub_channel
     *
     * @mbggenerated
     */
    public void setSubChannel(String subChannel) {
        this.subChannel = subChannel == null ? null : subChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.value
     *
     * @return the value of idx_value_manual.value
     *
     * @mbggenerated
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.value
     *
     * @param value the value for idx_value_manual.value
     *
     * @mbggenerated
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.created_at
     *
     * @return the value of idx_value_manual.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.created_at
     *
     * @param createdAt the value for idx_value_manual.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.created_by
     *
     * @return the value of idx_value_manual.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.created_by
     *
     * @param createdBy the value for idx_value_manual.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.updated_at
     *
     * @return the value of idx_value_manual.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.updated_at
     *
     * @param updatedAt the value for idx_value_manual.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idx_value_manual.updated_by
     *
     * @return the value of idx_value_manual.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idx_value_manual.updated_by
     *
     * @param updatedBy the value for idx_value_manual.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }
}