package com.zj.dao.mapper;

import com.zj.dao.model.IdxInfo;

public interface IdxInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    int insert(IdxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    int insertSelective(IdxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    IdxInfo selectByPrimaryKey(String indexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdxInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdxInfo record);
}