package com.zj.dao.mapper;

import com.zj.dao.model.IdxReportModel;
import com.zj.dao.model.IdxReportModelKey;

import java.util.List;

public interface IdxReportModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(IdxReportModelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    int insert(IdxReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    int insertSelective(IdxReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    IdxReportModel selectByPrimaryKey(IdxReportModelKey key);


    List<IdxReportModel> selectByReportId(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdxReportModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_report_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdxReportModel record);
}