package com.zj.dao.mapper;

import com.zj.dao.model.IdxValue;

import java.util.List;
import java.util.Map;

public interface IdxValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    int insert(IdxValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    int insertSelective(IdxValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    IdxValue selectByPrimaryKey(String id);

    List<IdxValue> selectByCondition(Map<String, String> map);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdxValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdxValue record);
}