package com.zj.dao.mapper;

import com.zj.dao.model.IdxValueManual;

import java.util.List;
import java.util.Map;

public interface IdxValueManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    int insert(IdxValueManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    int insertSelective(IdxValueManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    IdxValueManual selectByPrimaryKey(String id);


    List<IdxValueManual> selectByCondition(Map<String,String> id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdxValueManual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idx_value_manual
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdxValueManual record);
}